sudo: required

language: java

services:
  - docker

notifications:
  email: false

script:
  - mvn clean verify

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --settings .travis.settings.xml
